void trm_main(void);
void trm_init(void);
int trm_capture(char);
int trm_parse_buffer(void);
void buffer_clear(void);
void buffer_add_c(char);
void buffer_backs(void);
int help(void);
int ls(void);
int cd(void);
int sysinfo(void);
int exit_sh(void);
int here(void);
int cat (void);
int run (void);
int dump(void);
int clear(void);
int mini(void);
