int mini_init(char*, char*);
int start_mini_new(char*);
int start_mini_file(char*, char*);
int mini_main(void);
int mini_save(void);
int mini_load(char*);
int mini_capture(char);
void mini_add_c(char);
void mini_back_sp();
int mini_exit();
void ctrl_output(char*);
void ctrl_input(char*, char**);
void mini_clear(void);
int mini_new(void);
int mini_open(void);
